# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mom_pb2 as mom__pb2


class MessageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_unary(
        '/mom.MessageService/SendMessage',
        request_serializer=mom__pb2.MessageRequest.SerializeToString,
        response_deserializer=mom__pb2.MessageResponse.FromString,
        )
    self.ReceiveMessage = channel.unary_unary(
        '/mom.MessageService/ReceiveMessage',
        request_serializer=mom__pb2.MessageRequest.SerializeToString,
        response_deserializer=mom__pb2.MessageResponse.FromString,
        )


class MessageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    """Sends a message to a topic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceiveMessage(self, request, context):
    """Receives a message from a topic
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=mom__pb2.MessageRequest.FromString,
          response_serializer=mom__pb2.MessageResponse.SerializeToString,
      ),
      'ReceiveMessage': grpc.unary_unary_rpc_method_handler(
          servicer.ReceiveMessage,
          request_deserializer=mom__pb2.MessageRequest.FromString,
          response_serializer=mom__pb2.MessageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mom.MessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
